"""Markdown and HTML report writers for human-readable experiment summaries."""

import os
from typing import Any


def write_markdown_report(results: dict[str, Any], path: str) -> str:
    """Write a Markdown experiment report to *path* and return the path."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    text = _render_markdown(results)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    return path


def write_html_report(results: dict[str, Any], path: str) -> str:
    """Write a self-contained HTML experiment report to *path* and return the path."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    md = _render_markdown(results)
    html = _wrap_html(md, title="Pocket ML Lab Report")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(html)
    return path


def _render_markdown(results: dict[str, Any]) -> str:
    cfg = results.get("config", {})
    ds = results.get("dataset", {})
    evaluation = results.get("evaluation", {})
    model_results = results.get("results", [])
    task = cfg.get("task", "classification")

    lines = [
        "# Pocket ML Lab — Experiment Report",
        "",
        "## Configuration",
        "",
        f"| Key | Value |",
        f"|---|---|",
        f"| Dataset | `{cfg.get('csv_path', '')}` |",
        f"| Target | `{cfg.get('target', '')}` |",
        f"| Task | {task} |",
        f"| Test size | {cfg.get('test_size', '')} |",
        f"| Random seed | {cfg.get('seed', '')} |",
        "",
        "## Dataset Summary",
        "",
        f"| Stat | Value |",
        f"|---|---|",
        f"| Rows | {ds.get('n_rows', '')} |",
        f"| Columns | {ds.get('n_cols', '')} |",
        f"| Training samples | {ds.get('n_train', '')} |",
        f"| Test samples | {ds.get('n_test', '')} |",
        f"| Features | {', '.join(f'`{c}`' for c in ds.get('features', []))} |",
        "",
        "## Evaluation Summary",
        "",
        "| Item | Value |",
        "|---|---|",
        f"| Primary metric | `{evaluation.get('primary_metric', '')}` |",
        f"| Direction | {evaluation.get('direction', '')} is better |",
        f"| Best model | {evaluation.get('best_model', '')} |",
        f"| Best score | {evaluation.get('best_score', '')} |",
        "",
        "## Results",
        "",
    ]

    for mr in model_results:
        lines.append(f"### {mr.get('model', 'Model')}")
        lines.append("")
        metrics = mr.get("metrics", {})

        if task == "classification":
            lines += [
                "| Metric | Value |",
                "|---|---|",
                f"| Accuracy | {metrics.get('accuracy', '')} |",
                f"| Balanced Accuracy | {metrics.get('balanced_accuracy', '')} |",
                f"| Macro Precision | {metrics.get('macro_precision', '')} |",
                f"| Macro Recall | {metrics.get('macro_recall', '')} |",
                f"| Macro F1 | {metrics.get('macro_f1', '')} |",
                "",
            ]
            pcm = metrics.get("per_class", {})
            if pcm:
                lines += [
                    "**Per-class metrics**",
                    "",
                    "| Class | Precision | Recall | F1 | Support |",
                    "|---|---|---|---|---|",
                ]
                for cls, cm in pcm.items():
                    lines.append(
                        f"| {cls} | {cm.get('precision','')} | {cm.get('recall','')} "
                        f"| {cm.get('f1','')} | {cm.get('support','')} |"
                    )
                lines.append("")

            cm_data = metrics.get("confusion_matrix", {})
            if cm_data:
                classes = cm_data.get("classes", [])
                matrix = cm_data.get("matrix", [])
                lines += ["**Confusion matrix**", ""]
                header = "| True \\ Pred | " + " | ".join(str(c) for c in classes) + " |"
                sep = "|---|" + "---|" * len(classes)
                lines += [header, sep]
                for i, row in enumerate(matrix):
                    row_label = classes[i] if i < len(classes) else str(i)
                    lines.append(
                        f"| {row_label} | " + " | ".join(str(v) for v in row) + " |"
                    )
                lines.append("")

        else:
            lines += [
                "| Metric | Value |",
                "|---|---|",
                f"| MAE | {metrics.get('mae', '')} |",
                f"| RMSE | {metrics.get('rmse', '')} |",
                f"| R² | {metrics.get('r2', '')} |",
                "",
            ]

    lines += [
        "---",
        "",
        "*Generated by [Pocket ML Lab](https://github.com/get2salam/pocket-ml-lab)*",
    ]
    return "\n".join(lines)


def _wrap_html(markdown_text: str, title: str = "Report") -> str:
    """Wrap Markdown in a minimal HTML page with inline CSS (no external deps)."""
    escaped = markdown_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Convert basic Markdown to HTML for browser rendering
    lines_out = []
    in_table = False
    for line in escaped.split("\n"):
        if line.startswith("# "):
            lines_out.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("## "):
            lines_out.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("### "):
            lines_out.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("|"):
            if not in_table:
                lines_out.append("<table>")
                in_table = True
            if set(line.replace("|", "").replace("-", "").strip()) <= {""}:
                continue  # skip separator row
            cells = [c.strip() for c in line.strip("|").split("|")]
            tag = "th" if lines_out and lines_out[-1] == "<table>" else "td"
            row_html = "".join(f"<{tag}>{c}</{tag}>" for c in cells)
            lines_out.append(f"<tr>{row_html}</tr>")
        else:
            if in_table:
                lines_out.append("</table>")
                in_table = False
            if line.startswith("---"):
                lines_out.append("<hr>")
            elif line.startswith("**") and line.endswith("**"):
                lines_out.append(f"<strong>{line[2:-2]}</strong>")
            elif line == "":
                lines_out.append("<br>")
            else:
                lines_out.append(f"<p>{line}</p>")
    if in_table:
        lines_out.append("</table>")

    body = "\n".join(lines_out)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 2rem auto; padding: 0 1rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td {{ border: 1px solid #ccc; padding: 0.4rem 0.8rem; text-align: left; }}
  th {{ background: #f0f0f0; }}
  h1, h2, h3 {{ color: #1a1a2e; }}
  code {{ background: #f5f5f5; padding: 0.1rem 0.3rem; border-radius: 3px; }}
  hr {{ border: none; border-top: 1px solid #ccc; }}
</style>
</head>
<body>
{body}
</body>
</html>
"""
